In [1]:
import torch
import numpy as np
import pandas as pd
from torch.autograd import Variable

In [2]:
a = np.array([[1,2],[2,1]], dtype = float)
b = pd.DataFrame([[3,4],[4,3]], dtype = float)


In [3]:
x = torch.ones(2,2, dtype = float)
y = torch.from_numpy(a)

In [4]:
x.add_(y)

tensor([[2., 3.],
        [3., 2.]], dtype=torch.float64)

In [5]:
XV = Variable(x, requires_grad = True)

In [6]:
YV = XV + 2
ZV = YV * 2

In [10]:
err = ZV * ZV - YV

In [95]:
x = torch.randn(3)
x = Variable(x, requires_grad = True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)
x.grad

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])

In [20]:

err.backward(torch.ones(2,2))

AttributeError: 'Tensor' object has no attribute 'zero_grad'

In [15]:
print(XV.grad)

tensor([[31., 39.],
        [39., 31.]], dtype=torch.float64)
